### ISSUE TITLE
Exception happened during processing of request

### ISSUE THREAD

**Issue by werdeil** [anxuae/pycups-notify#1]
I got the following issue, any idea?

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57540)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/Users/Vincent/Documents/git/venv/pibooth/lib/python3.7/site-packages/cups_notify/listener.py", line 67, in do_PUT
    evts.append(event.CupsEvent(data))
  File "/Users/Vincent/Documents/git/venv/pibooth/lib/python3.7/site-packages/cups_notify/event.py", line 43, in __init__
    self.timestamp = self._parse_date(data)
  File "/Users/Vincent/Documents/git/venv/pibooth/lib/python3.7/site-packages/cups_notify/event.py", line 50, in _parse_date
    return datetime.strptime(date, "%a, %d %b %Y %H:%M:%S GMT")
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data 'Sun, 22 Mar 2020 15:43:32 GMT' does not match format '%a, %d %b %Y %H:%M:%S GMT'
```

**Comment by anxuae** [comment]
This is due to the use of pygame 2.0 which set the language/charset from the locale config.
Thus on french PC, datetime module parse date expecting days name in french.

However CUPS server always send event with date in english.
